apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysqldump.fullname" . }}
  labels:
    {{- include "mysqldump.labels" . | nindent 4 }}
data:
  MYSQL_HOST: {{ .Values.mysql.host | quote }}
  MYSQL_USERNAME: {{ .Values.mysql.username | quote }}
  MYSQL_PORT: {{ .Values.mysql.port | quote }}
  MYSQL_OPTS: {{ .Values.mysql.dumpOptions | quote }}
  KEEP_DAYS: {{ .Values.housekeeping.keepDays | quote }}
{{- if .Values.upload.openstack.enabled }}
  OS_AUTH_URL: {{ .Values.upload.openstack.authUrl }}
  OS_PROJECT_NAME: {{ .Values.upload.openstack.project }}
  OS_PROJECT_DOMAIN_NAME: {{ .Values.upload.openstack.projectDomain }}
  OS_USERNAME: {{ .Values.upload.openstack.user }}
  OS_USER_DOMAIN_NAME: {{ .Values.upload.openstack.userDomain }}
{{- end }}
{{- if .Values.upload.s3.enabled }}
  S3_ENDPOINT: {{ .Values.upload.s3.endpoint }}
  S3_ACCESSKEY: {{ .Values.upload.s3.accesskey }}
  S3_BUCKETNAME: {{ .Values.upload.s3.bucketname }}
  S3_REGION: {{ .Values.upload.s3.region }}
{{- end }}
