{{- if ne .Values.schedule "now" -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "mysqldump.fullname" . }}
  labels:
    {{- include "mysqldump.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        {{- include "mysqldump.labels" . | nindent 8 }}
        cronjob-name: {{ template "mysqldump.fullname" . }}
    spec:
      backoffLimit: 1
      template:
{{- $file := .Files.Get "files/job.tpl" }}
{{ tpl $file . | indent 8 }}
{{ end }}
