{{- if .Values.upload.googlestoragebucket.enabled }}
{{- if not .Values.upload.googlestoragebucket.existingSecret }}
{{- if not .Values.upload.googlestoragebucket.usingGCPController }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysqldump.gcpsecretName" . }}
  labels:
    {{- include "mysqldump.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.upload.googlestoragebucket.secretFileName }}: {{ .Values.upload.googlestoragebucket.jsonKeyfile | quote }}
{{ end }}
{{ end }}
{{ end }}
