{{- if .Values.upload.ssh.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "mysqldump.fullname" . }}-ssh-privatekey"
  labels:
    {{- include "mysqldump.labels" . | nindent 4 }}
type: Opaque
stringData:
  id_rsa: {{ .Values.upload.ssh.privatekey | quote }}
{{- end }}
