apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "mysqldump.fullname" . }}"
  labels:
    {{- include "mysqldump.labels" . | nindent 4 }}
type: Opaque
data:
{{- if and (.Values.mysql.password) (not .Values.mysql.existingSecret) }}
  MYSQL_PWD: {{ .Values.mysql.password | b64enc | quote }}
{{- else }}
  MYSQL_PWD: {{ randAlphaNum 40 | b64enc | quote }}
{{- end }}
{{- if and (.Values.upload.openstack.enabled) (not .Values.upload.openstack.existingSecret) }}
  OS_PASSWORD: {{ .Values.upload.openstack.password | b64enc | quote }}
{{- end }}
