{{- if .Values.authProxy.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "visual-regression-tracker.fullname" . }}-auth
  labels:
    {{- include "visual-regression-tracker.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.authProxy.podDisruptionBudget | nindent 2}}
  selector:
    matchLabels:
      {{- include "visual-regression-tracker.selectorLabels" . | nindent 6 }}
      component: auth-proxy
{{- end -}}
