{{ if and .Values.authProxy.basicAuth.password (not .Values.secrets.authProxy.useExisting) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "visual-regression-tracker.fullname" . }}-auth
  labels:
    {{- include "visual-regression-tracker.labels" . | nindent 4 }}
    component: auth-proxy
type: Opaque
data:
  {{ .Values.secrets.authProxy.secretKey }}: {{ .Values.authProxy.basicAuth.password | b64enc | quote }}
{{ end }}
