apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  env.sh: |
    #!/bin/sh
    # dummy file which replaces env.sh to be able to use rofs
    cat env-config.js
  env-config.js: |
    window._env_ = {
        REACT_APP_API_URL: "http://localhost:4200",
        PORT: "8080",
        VRT_VERSION: "5.0.0",
    }
