apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  env.sh: |
    #!/bin/sh
    # dummy file which replaces env-config.js creation to be able to use rofs
    cat env-config.js
  env-config.js: |
    window._env_ = {
        REACT_APP_API_URL: "{{ .Values.vrtConfig.reactAppApiUrl }}",
        PORT: "{{ .Values.ui.service.port }}",
        VRT_VERSION: "{{ .Chart.AppVersion }}",
    }
