{{ if and .Values.vrtConfig.elasticsearch.pass (not .Values.secrets.elasticsearch.useExisting) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "visual-regression-tracker.elasticsearchSecretName" . }}
  labels:
    {{- include "visual-regression-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.elasticsearch.secretKey }}: {{ .Values.vrtConfig.elasticsearch.pass | b64enc | quote }}
{{ end }}
{{ if not .Values.secrets.jwt.useExisting }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "visual-regression-tracker.jwtSecretName" . }}
  labels:
    {{- include "visual-regression-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.jwt.secretKey }}: {{ .Values.vrtConfig.jwt.pass | b64enc | quote }}
{{ end }}
{{ if not .Values.secrets.postgresql.useExisting }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "visual-regression-tracker.postgresqlSecretName" . }}
  labels:
    {{- include "visual-regression-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.postgresql.secretKey }}: {{ .Values.vrtConfig.postgresql.pass | b64enc | quote }}
{{ end }}
{{ if and (or .Values.vrtConfig.defaults.apiKey .Values.vrtConfig.defaults.pass) (not .Values.secrets.defaults.useExisting) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "visual-regression-tracker.vrtSecretName" . }}
  labels:
    {{- include "visual-regression-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.defaults.secretKey }}: {{ tpl (.Files.Get "files/seed.ts") $ | b64enc }}
{{ end }}
