apiVersion: v1
kind: Service
metadata:
  name: {{ include "visual-regression-tracker.fullname" . }}-api
  labels:
    {{- include "visual-regression-tracker.labels" . | nindent 4 }}
    component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "visual-regression-tracker.selectorLabels" . | nindent 4 }}
