apiVersion: v1
kind: Service
metadata:
  name: {{ include "visual-regression-tracker.fullname" . }}-ui
  labels:
    {{- include "visual-regression-tracker.labels" . | nindent 4 }}
    component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "visual-regression-tracker.selectorLabels" . | nindent 4 }}
