{{- if .Values.php.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nginx-php-fpm.fullname" . }}-php
  labels:
    component: php
    {{- include "nginx-php-fpm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nginx-php-fpm.fullname" . }}
  minReplicas: {{ .Values.php.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.php.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.php.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.php.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.php.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.php.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
