name: kubeval

on:
  pull_request:

jobs:
  kubeval-chart:
    runs-on: ubuntu-latest
    needs: lint-chart
    strategy:
      matrix:
        k8s:
          - v1.16.4
          - v1.17.4
          - v1.18.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh 
