name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.16.15
          - v1.17.11
          - v1.18.6
          - v1.19.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: lint
          config: .github/ct.yaml

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.0.0
        with:
          config: .github/kind-config.yaml
          node_image: kindest/node:${{ matrix.k8s }}
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: install
          config: .github/ct.yaml
